- 👋 Hi, I’m marwa tarek
- 👀 I’m interested in the role of AI in diagnosis medical images especially radiological images ...
- 🌱 I’m currently learning data science and machine learning...
- 💞️ I’m looking to collaborate on projects serve medical field...
- 📫 How to reach me marwatarek467@gmail.com...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...

<!---
marwa-pixel/marwa-pixel is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
